variables:
  FF_USE_FASTZIP: 1

image: rust:buster

stages:
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

before_script:
  - docker info

build:
  tags:
    - docker
  stage: build
  script:
    - apt-get update && apt-get install -y firefox-esr
    - cargo install wasm-pack
    - cargo build
    - cargo test
    - wasm-pack test --headless --firefox
  cache:
    key: build-cache
    paths:
      - .cargo/
      - target/
