[package]
name = "tagged-base64-macros"
description = "Procedural macros associated with tagged-base64"
version = "0.2.0"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2018"

[lib]
proc-macro = true

[features]
default-features = ["serde"]
serde = []

[dependencies]
ark-std = { version = "0.3.0", default-features = false }
syn = { version = "1.0", features = ["extra-traits"] }
quote = "1.0"

[dev-dependencies]
ark-serialize = { version = "0.3.0", default-features = false, features = ["derive"] }
ark-bls12-381 = { version = "0.3.0", default-features = false, features = ["curve"] }
bincode = { version = "1.3.3", default-features = false }
rand_chacha = { version = "0.3.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.61"
